const cron = require('node-cron');
const Event = require('../models/Event');
const EventRegistration = require('../models/EventRegistration');
const QRCodeModel = require('../models/QRCode');
const QRCode = require('qrcode');
const PDFDocument = require('pdfkit');
const axios = require('axios');

// Helper function to send email with attachment via Brevo
const sendEmailWithAttachment = async (to, subject, htmlContent, pdfBase64, fileName) => {
  if (!process.env.BREVO_API_KEY) {
    console.error('FATAL ERROR: BREVO_API_KEY is missing in environment variables!');
    return;
  }

  try {
    const response = await axios.post(
      'https://api.brevo.com/v3/smtp/email',
      {
        sender: {
          email: process.env.BREVO_SENDER_EMAIL || 'chetanshende1111@gmail.com',
          name: 'EventSync'
        },
        to: [{ email: to }],
        subject: subject,
        htmlContent: htmlContent,
        attachment: [
          {
            content: pdfBase64,
            name: fileName
          }
        ]
      },
      {
        headers: {
          'api-key': process.env.BREVO_API_KEY,
          'Content-Type': 'application/json'
        }
      }
    );
    return response.data;
  } catch (error) {
    console.error('Email sending failed:', error.response?.data || error.message);
    throw error;
  }
};

// Generate QR Code PDF
const generateQRCodePDF = async (qrToken, userName, eventName, eventDate, eventLocation) => {
  return new Promise(async (resolve, reject) => {
    try {
      // Generate QR code as data URL
      const qrDataUrl = await QRCode.toDataURL(qrToken);

      // Create PDF
      const doc = new PDFDocument({ size: 'A4', margin: 50 });
      const chunks = [];

      doc.on('data', (chunk) => chunks.push(chunk));
      doc.on('end', () => {
        const pdfBuffer = Buffer.concat(chunks);
        resolve(pdfBuffer.toString('base64'));
      });
      doc.on('error', reject);

      // Header
      doc.fontSize(24)
         .fillColor('#4f46e5')
         .text('EventSync', { align: 'center' })
         .moveDown(0.5);

      doc.fontSize(18)
         .fillColor('#000000')
         .text('Event Entry Pass', { align: 'center' })
         .moveDown(1);

      // Event Details
      doc.fontSize(12)
         .fillColor('#666666')
         .text('Attendee Name:', { continued: true })
         .fillColor('#000000')
         .text(` ${userName}`)
         .moveDown(0.5);

      doc.fillColor('#666666')
         .text('Event:', { continued: true })
         .fillColor('#000000')
         .text(` ${eventName}`)
         .moveDown(0.5);

      doc.fillColor('#666666')
         .text('Date & Time:', { continued: true })
         .fillColor('#000000')
         .text(` ${new Date(eventDate).toLocaleString()}`)
         .moveDown(0.5);

      doc.fillColor('#666666')
         .text('Location:', { continued: true })
         .fillColor('#000000')
         .text(` ${eventLocation}`)
         .moveDown(2);

      // QR Code
      doc.fontSize(14)
         .fillColor('#4f46e5')
         .text('Your Entry QR Code', { align: 'center' })
         .moveDown(0.5);

      // Add QR code image (convert data URL to buffer)
      const qrImageBuffer = Buffer.from(qrDataUrl.split(',')[1], 'base64');
      doc.image(qrImageBuffer, {
        fit: [200, 200],
        align: 'center',
        valign: 'center'
      });

      doc.moveDown(2);

      // Instructions
      doc.fontSize(10)
         .fillColor('#666666')
         .text('Please show this QR code at the event entrance for check-in.', { align: 'center' })
         .moveDown(0.5)
         .text('Keep this pass safe and accessible on your device.', { align: 'center' });

      // Footer
      doc.moveDown(2)
         .fontSize(8)
         .fillColor('#999999')
         .text('Generated by EventSync - Event Management System', { align: 'center' })
         .text(`Generated on: ${new Date().toLocaleString()}`, { align: 'center' });

      doc.end();
    } catch (error) {
      reject(error);
    }
  });
};

// Check and send reminders for upcoming events
const checkAndSendReminders = async () => {
  try {
    const now = new Date();
    const reminderTime = new Date(now.getTime() + 15 * 60 * 1000); // 15 minutes from now
    const reminderTimeEnd = new Date(now.getTime() + 16 * 60 * 1000); // 16 minutes from now

    // Find events starting in 15-16 minutes
    const upcomingEvents = await Event.find({
      startDateTime: {
        $gte: reminderTime,
        $lt: reminderTimeEnd
      }
    });

    console.log(`[Event Reminder] Checking for events... Found ${upcomingEvents.length} events starting in 15 minutes`);

    for (const event of upcomingEvents) {
      // Get all approved registrations for this event
      const registrations = await EventRegistration.find({
        event: event._id,
        status: 'approved'
      }).populate('user');

      console.log(`[Event Reminder] Event "${event.eventName}" has ${registrations.length} approved attendees`);

      for (const registration of registrations) {
        try {
          // Find or get QR code for this registration
          let qrCode = await QRCodeModel.findOne({
            event: event._id,
            user: registration.user._id,
            registration: registration._id
          });

          if (!qrCode) {
            console.log(`[Event Reminder] No QR code found for user ${registration.user.email}, skipping...`);
            continue;
          }

          // Generate PDF with QR code
          const pdfBase64 = await generateQRCodePDF(
            qrCode.token,
            registration.user.fullName,
            event.eventName,
            event.startDateTime,
            event.locationType === 'online' ? event.locationValue : event.locationValue
          );

          // Send email with PDF attachment
          const emailHtml = `
            <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;">
              <h2 style="color: #4f46e5;">⏰ Event Starting Soon!</h2>
              <p>Hi ${registration.user.fullName},</p>
              <p>This is a friendly reminder that your event is starting in <strong>15 minutes</strong>!</p>

              <div style="background: #f3f4f6; padding: 20px; border-radius: 8px; margin: 20px 0;">
                <h3 style="margin-top: 0; color: #1f2937;">Event Details:</h3>
                <p><strong>Event:</strong> ${event.eventName}</p>
                <p><strong>Start Time:</strong> ${new Date(event.startDateTime).toLocaleString()}</p>
                <p><strong>Location:</strong> ${event.locationType === 'online' ? '🌐 Online - ' + event.locationValue : '📍 ' + event.locationValue}</p>
              </div>

              <div style="background: #dbeafe; padding: 15px; border-radius: 8px; margin: 20px 0; border-left: 4px solid #3b82f6;">
                <p style="margin: 0; color: #1e40af;">
                  <strong>📎 Your QR Code is attached!</strong><br/>
                  Please have it ready for quick check-in at the entrance.
                </p>
              </div>

              <div style="background: #fef3c7; padding: 15px; border-radius: 8px; margin: 20px 0;">
                <p style="margin: 0; color: #92400e;">
                  <strong>💡 Tips:</strong><br/>
                  • Arrive a few minutes early<br/>
                  • Have your QR code ready on your device<br/>
                  • Check your internet connection if it's an online event
                </p>
              </div>

              <p>We look forward to seeing you at the event! 🎉</p>
              <p>Best regards,<br/>EventSync Team</p>
            </div>
          `;

          await sendEmailWithAttachment(
            registration.user.email,
            `⏰ Starting in 15 mins: ${event.eventName} - QR Code Attached`,
            emailHtml,
            pdfBase64,
            `${event.eventName.replace(/[^a-z0-9]/gi, '_')}_QR_Code.pdf`
          );

          console.log(`[Event Reminder] Sent reminder to ${registration.user.email} for event "${event.eventName}"`);

        } catch (emailError) {
          console.error(`[Event Reminder] Failed to send reminder to ${registration.user.email}:`, emailError.message);
        }
      }
    }
  } catch (error) {
    console.error('[Event Reminder] Error in reminder service:', error);
  }
};

// Initialize the cron job
const initEventReminderService = () => {
  // Run every minute to check for events
  cron.schedule('* * * * *', () => {
    checkAndSendReminders();
  });

  console.log('[Event Reminder Service] ✅ Started - Checking every minute for events starting in 15 minutes');
};

module.exports = { initEventReminderService };
